rule_sets = {
    "1": {
        "name": "Italian",
        "rules": [
            (r'\b(AC[!.,?-]?)\b', r'<say-as interpret-as="characters">AC</say-as>'),
            (r'\b(CV[!.,?-]?)\b', r'<say-as interpret-as="characters">CV</say-as>'),
            (r'\b(ID[!.,?-]?)\b', r'<say-as interpret-as="characters">ID</say-as>'),
            (r'\b(V[!.,?-]?)\b', r'<say-as interpret-as="characters">V</say-as>'),
            (r'\b(X[!.,?-]?)\b', r'<say-as interpret-as="characters">X</say-as>'),
            (r'\bAir-Gap\b', r'<phoneme alphabet="ipa" ph="ɛɚ">Air</phoneme>-<phoneme alphabet="ipa" ph="gap">Gap</phoneme>'),
            (r'\bampere\b', r'ampére'),
            (r'\banodi\b', r'<phoneme alphabet="ipa" ph="ˈanodi">anodi</phoneme>'),
            (r'\banodo\b', r'<phoneme alphabet="ipa" ph="ˈanodo">anodo</phoneme>'),
            (r'\bappropriate\b', r'<phoneme alphabet="ipa" ph="apːropriate">appropriate</phoneme>'),
            (r'\bBEV\b', r'<say-as interpret-as="characters">BEV</say-as>'),
            (r'\bblackout\b', r'<phoneme alphabet="ipa" ph="ˈblækaʊt">blackout</phoneme>'),
            (r'\bBuckeye\b', r'<phoneme alphabet="ipa" ph="ˈbʌkaɪ">Buckeye</phoneme>'),
            (r'\bcatodi\b', r'<phoneme alphabet="ipa" ph="ˈkatodi">catodi</phoneme>'),
            (r'\bcatodo\b', r'<phoneme alphabet="ipa" ph="ˈkatodo">catodo</phoneme>'),
            (r'\bcells\b', r'<phoneme alphabet="ipa" ph="ˈsɛlz">cells</phoneme>'),
            (r'\bcentrifughi\b', r'centrífughi'),
            (r'\bCH4\b', r'<say-as interpret-as="characters">CH4</say-as>'),
            (r'\bCO\b', r'<say-as interpret-as="characters">CO</say-as>'),
            (r'\bCO2\b', r'<say-as interpret-as="characters">CO2</say-as>'),
            (r'\bCoenergia\b', r'<phoneme alphabet="ipa" ph="ko.e.ner.ʤˈia">Coenergia</phoneme>'),
            (r'\bCogging\b', r'<phoneme alphabet="ipa" ph="ˈko.gːing">Cogging</phoneme>'),
            (r'\bcomplete\b', r'<phoneme alphabet="ipa" ph="complete">complete</phoneme>'),
            (r'\bcore\b', r'<phoneme alphabet="ipa" ph="kɔɹ">core</phoneme>'),
            (r'\bdarvela\b', r'<phoneme alphabet="ipa" ph="ˈdar.ve.la">darvela</phoneme>'),
            (r'\bDesideri\b', r'desìderi'),
            (r'\bdiodi\b', r'dìodi'),
            (r'\bdiodo\b', r'dìodo'),
            (r'\bDischarge\b', r'<phoneme alphabet="ipa" ph="disˈʧarʤ">Discharge</phoneme>'),
            (r'\bdomini\b', r'<phoneme alphabet="ipa" ph="doˈmini">domini</phoneme>'),
            (r'\bduty ratio\b', r'duty <phoneme alphabet="ipa" ph="rɛj.ʤio">ratio</phoneme>'),
            (r'\belettrici\b', r'<phoneme alphabet="ipa" ph="elˈettri.ʧi">elettrici</phoneme>'),
            (r'\bFaraday\b', r'<phoneme alphabet="ipa" ph="ˈfaˌra.da.i">Faraday</phoneme>'),
            (r'\bfeedback\b', r'<phoneme alphabet="ipa" ph="ˈfidˌbak">feedback</phoneme>'),
            (r'\bfile\b', r'<phoneme alphabet="ipa" ph="fˈa.il">file</phoneme>'),
            (r'\bfuel cell\b', r'<lang xml:lang="en-US">fuel cell</lang>'),
            (r'\bgalvanostato\b', r'<phoneme alphabet="ipa" ph="gal.va.nˈos.ta.to ">galvanostato</phoneme>'),
            (r'\bgen\b', r'gén'),
            (r'\bgiri/min\b', r'giri al minuto'),
            (r'\bjoule\b', r'<phoneme alphabet="ipa" ph="ˈd͡ʒawl">joule</phoneme>'),
            (r'\bkilohertz\b', r'<phoneme alphabet="ipa" ph="ˈkilo.ertz">kilohertz</phoneme>'),
            (r'\bkilowatt\b', r'<phoneme alphabet="ipa" ph="ˈkilo.vatː">kilowatt</phoneme>'),
            (r'\bKirchoff\b', r'<phoneme alphabet="ipa" ph="ˈkir.kofː">Kirchoff</phoneme>'),
            (r'\blasciatemelo\b', r'<phoneme alphabet="ipa" ph="la.ʃʃˈa.te.melˌo">lasciatemelo</phoneme>'),
            (r'\bmatematici\b', r'<phoneme alphabet="ipa" ph="ma.te.ˈma.ti.ˌtʃːi">matematici</phoneme>'),
            (r'\bmodellino\b', r'modéllino'),
            (r'\bMOSFET\b', r'<phoneme alphabet="ipa" ph="ˈmos.fet">MOSFET</phoneme>'),
            (r'\bmuoverci\b', r'<phoneme alphabet="ipa" ph="muɔ.ver.ʧi">muoverci</phoneme>'),
            (r'\bOracle\b', r'<phoneme alphabet="ipa" ph="ˈɔɹəkɔl">Oracle</phoneme>'),
            (r'\borizzontale\b', r'<phoneme alphabet="ipa" ph="oriʣonˌtale">orizzontale</phoneme>'),
            (r'\bottimizzati\b', r'<phoneme alphabet="ipa" ph="otti.mi.zˈza.ti">ottimizzati</phoneme>'),
            (r'\bPEM\b', r'<phoneme alphabet="ipa" ph="ˈpem">PEM</phoneme>'),
            (r'\bprincipi\b', r'princípi'),
            (r'\bPSIM\b', r'<say-as interpret-as="characters">P</say-as>SIM'),
            (r'\bsincrone\b', r'síncrone'),
            (r'\bslave\b', r'<phoneme alphabet="ipa" ph="s.leiv">slave</phoneme>'),
            (r'\bstate\b', r'<phoneme alphabet="ipa" ph="state">state</phoneme>'),
            (r'\bstop and go\b', r'stop and <phoneme alphabet="ipa" ph="ˈgːoʊ">go</phoneme>'),
            (r'\btenetelo\b', r'<phoneme alphabet="ipa" ph="te.nɛ.telo">tenetelo</phoneme>'),
            (r'cost-to-go', r'cost-to-<phoneme alphabet="ipa" ph="ɡoʊ">go</phoneme>'),
        ]
    }
}
