rule_sets = {
    "1": {
        "name": "general",
        "rules": [
            (r'\bAll Access\b', r'<lang xml:lang="en-US">All Access</lang>'),
            (r'\bCollectibles\b', r'<lang xml:lang="en-US">Collectibles</lang>'),
            (r'\bCorporate and Platform Services\b', r'<lang xml:lang="en-US">Corporate and Platform Services</lang>'),
            (r'\bCorporate\b', r'<lang xml:lang="en-US">Corporate</lang>'),
            (r'\bESPN\b', r'<lang xml:lang="en-US">ESPN</lang>'),
            (r'\bFanCash\b', r'<lang xml:lang="en-US">Fan Cash</lang>'),
            (r'\bFanatics Betting and Gaming\b', r'<lang xml:lang="en-US">Fanatics Betting and Gaming</lang>'),
            (r'\bFanatics Collect\b', r'<lang xml:lang="en-US">Fanatics Collect</lang>'),
            (r'\bFanatics Collectibles\b', r'<lang xml:lang="en-US">Fanatics Collectibles</lang>'),
            (r'\bFanatics Commerce\b', r'<lang xml:lang="en-US">Fanatics Commerce</lang>'),
            (r'\bFanatics Corporate\b', r'<lang xml:lang="en-US">Fanatics Corporate</lang>'),
            (r'\bFanatics Events\b', r'<lang xml:lang="en-US">Fanatics Events</lang>'),
            (r'\bFanatics Fest\b', r'<lang xml:lang="en-US">Fanatics Fest</lang>'),
            (r'\bFanatics Foundation\b', r'<lang xml:lang="en-US">Fanatics Foundation</lang>'),
            (r'\bCorporate and Platform Services\b', r'<lang xml:lang="en-US">Corporate and Platform Services</lang>'),
            (r'\bSportsbook\b', r'<lang xml:lang="en-US">Sportsbook</lang>'),
            (r'\bfandom\b', r'<lang xml:lang="en-US">fandom</lang>'),
            (r'\biGaming\b', r'<lang xml:lang="en-US">iGaming</lang>'),
            (r'\bJacksonville\b', r'<lang xml:lang="en-US">Jacksonville</lang>'),
            (r'\bMake-A-Wish America\b', r'<lang xml:lang="en-US">Make-A-Wish America</lang>'),
            (r'\bManchester\b', r'<lang xml:lang="en-US">Manchester</lang>'),
            (r'\bMarvel\b', r'<lang xml:lang="en-US">Marvel</lang>'),
            (r'\bMichael Rubin\b', r'<lang xml:lang="en-US">Michael Rubin</lang>'),
            (r'\bMLB Debut\b', r'<lang xml:lang="en-US">MLB Debut</lang>'),
            (r'\bMLB\b', r'<lang xml:lang="en-US">MLB</lang>'),
            (r'\bMVP Buyback\b', r'<lang xml:lang="en-US">MVP Buyback</lang>'),
            (r'\bNBA\b', r'<lang xml:lang="en-US">NBA</lang>'),
            (r'\bNFL\b', r'<lang xml:lang="en-US">NFL</lang>'),
            (r'\bPWCC\b', r'<lang xml:lang="en-US">PWCC</lang>'),
            (r'\bStar Wars\b', r'<lang xml:lang="en-US">Star Wars</lang>'),
            (r'\bStarting Lineup\b', r'<lang xml:lang="en-US">Starting Lineup</lang>'),
            (r'\bTopps\b', r'<lang xml:lang="en-US">Topps</lang>'),
            (r'\bWWE\b', r'<lang xml:lang="en-US">WWE</lang>'),
        ]
    },
}
