rule_sets = {
    "1": {
        "name": "cs-cz",
        "rules": [
            (r'\bAI\b', r'<phoneme alphabet="ipa" ph="ˈɛj ˈaːj">AI</phoneme>'),
            (r'\bChat\b', r'<phoneme alphabet="ipa" ph="t͡ʃɛt">Chat</phoneme>'),
            (r'\bchatové\b', r'<phoneme alphabet="ipa" ph="t͡ʃɛtovɛː">chatové</phoneme>'),
            (r'\bcloudové\b', r'<phoneme alphabet="ipa" ph="ˈklaudovɛː">cloudové</phoneme>'),
            (r'\bcloudovými\b', r'<phoneme alphabet="ipa" ph="klaudoviːmi">cloudovými</phoneme>'),
            (r'\bDále\b', r'<phoneme alphabet="ipa" ph="ˈdaːlɛ">Dále</phoneme>'),
            (r'\bDocuSign\b', r'<phoneme alphabet="ipa" ph="dokusaːjn">DocuSign</phoneme>'),
            (r'\bdržitele\b', r'<phoneme alphabet="ipa" ph="ˈdrʒɪtɛlɛ">držitele</phoneme>'),
            (r'\be-mailech\b', r'<phoneme alphabet="ipa" ph="ˈiːmejlexː">e-mailech</phoneme>'),
            (r'\be-mailová\b', r'<phoneme alphabet="ipa" ph="ˈiːmejlɔʋaː">e-mailová</phoneme>'),
            (r'\be-mailové\b', r'<phoneme alphabet="ipa" ph="ˈiːmejlɔʋɛː">e-mailové</phoneme>'),
            (r'\be-mailového\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjlɔʋɛːɦo">e-mailového</phoneme>'),
            (r'\be-mailovém\b', r'<phoneme alphabet="ipa" ph="iːmaɪlovɛːm">e-mailovém</phoneme>'),
            (r'\be-mailových\b', r'<phoneme alphabet="ipa" ph="iːmaɪloviːx">e-mailových</phoneme>'),
            (r'\be-mailovým\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjloviːm">e-mailovým</phoneme>'),
            (r'\be-mailovými\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjloviːmɪ">e-mailovými</phoneme>'),
            (r'\bGmailu\b', r'<phoneme alphabet="ipa" ph="ˈd͡ʒiːmɛjlu">Gmailu</phoneme>'),
            (r'\bmalwarem\b', r'<phoneme alphabet="ipa" ph="malvɛːrɛm">malwarem</phoneme>'),
            (r'\bmalwaru\b', r'<phoneme alphabet="ipa" ph="malvɛːru">malwaru</phoneme>'),
            (r'\bověřte\b', r'<phoneme alphabet="ipa" ph="ovjɛr̝tɛ">ověřte</phoneme>'),
            (r'\bPINy\b', r'<phoneme alphabet="ipa" ph="ˈpɪnɪ">PINy</phoneme>'),
            (r'\bprvé\b', r'<phoneme alphabet="ipa" ph="pr.vˈɛː">prvé</phoneme>'),
            (r'\bransonwaru\b', r'<phoneme alphabet="ipa" ph="raŋsomvɛːru">ransonwaru</phoneme>'),
            (r'\bscreeningů\b', r'<phoneme alphabet="ipa" ph="ˈskriːnɪnguː">screeningů</phoneme>'),
            (r'\bsplnit\b', r'<phoneme alphabet="ipa" ph="ˈsplɲɪt">splnit</phoneme>'),
            (r'\bsplňovat\b', r'<phoneme alphabet="ipa" ph="ˈsplɲovat">splňovat</phoneme>'),
            (r'\btvrdí\b', r'<phoneme alphabet="ipa" ph="ˈtvrɟiː">tvrdí</phoneme>'),
            (r'\bID\b', r'<phoneme alphabet="ipa" ph="ˈajˈdiː">ID</phoneme>'),
            (r'\bGPS\b', r'<phoneme alphabet="ipa" ph="ˈd͡ʒiːˈpiːˈɛs">GPS</phoneme>'),
            (r'\bMS\b', r'<phoneme alphabet="ipa" ph="ˈemˈes">MS</phoneme>'),
            (r'\bfirmwaru\b', r'<phoneme alphabet="ipa" ph="ˈfɪrmwaru">firmwaru</phoneme>'),
            (r'\bHackeři\b', r'<phoneme alphabet="ipa" ph="ˈhɛt͡ʃɛɾi">Hackeři</phoneme>'),
            (r'\be-mailům\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjluːm">e-mailům</phoneme>'),
            (r'\bkondice\b', r'<phoneme alphabet="ipa" ph="ˈkɔndɪt͡se">kondice</phoneme>'),
            (r'\bConvention\b', r'<phoneme alphabet="ipa" ph="kənˈvɛnʃən">Convention</phoneme>'),
            (r'\bcloudových\b', r'<phoneme alphabet="ipa" ph="ˈklaudoviːx">cloudových</phoneme>'),
            (r'\bransomware\b', r'<phoneme alphabet="ipa" ph="ˈrænsəmˌwɛər">ransomware</phoneme>'),
            (r'\bransomwaru\b', r'<phoneme alphabet="ipa" ph="ˈransomwaru">ransomwaru</phoneme>'),
            (r'\bStealers\b', r'<phoneme alphabet="ipa" ph="ˈstiːlərz">Stealers</phoneme>'),
            (r'\bThomasi\b', r'<phoneme alphabet="ipa" ph="ˈtɔmasi">Thomasi</phoneme>'),
            (r'\bTeda\b', r'<phoneme alphabet="ipa" ph="ˈtɛda">Teda</phoneme>'),
            (r'\búkolů\b', r'<phoneme alphabet="ipa" ph="ˈuːkoluː">úkolů</phoneme>'),
            (r'\bčtvrtletí\b', r'<phoneme alphabet="ipa" ph="ˈt͡ʃtvr̩dlɛciː">čtvrtletí</phoneme>'),
            (r'\be-mailem\b', r'<phoneme alphabet="ipa" ph="ˈiːmejlem">e-mailem</phoneme>'),
            (r'\bHR\b', r'<phoneme alphabet="ipa" ph="ˈɛjt͡ʃ aːr">HR</phoneme>'),
            (r'\bindície\b', r'<phoneme alphabet="ipa" ph="ˈɪndiːt͡siːjɛ">indície</phoneme>'),
        ]
    },
    "2": {
        "name": "de-de",
        "rules": [
            (r'\bbot\b', r'<phoneme alphabet="ipa" ph="bɔt">bot</phoneme>'),
            (r'\bbotnet\b', r'<phoneme alphabet="ipa" ph="bˈɔtnət">botnet</phoneme>'),
            (r'\bEngineering\b', r'<phoneme alphabet="ipa" ph="ˈɛndʒəˈnɪɹɪŋ">Engineering</phoneme>'),
            (r'\bPhishing\b', r'<phoneme alphabet="ipa" ph="ˈfɪʃɪŋ">Phishing</phoneme>'),
            (r'\bgepostet\b', r'<phoneme alphabet="ipa" ph="ɡəpˈɔstət">gepostet</phoneme>'),
            (r'\bHijacking\b', r'<phoneme alphabet="ipa" ph="ˈhaɪˌdʒækɪŋ">Hijacking</phoneme>'),
            (r'\bKeylogger\b', r'<phoneme alphabet="ipa" ph="kˈiːlɒɡə">Keylogger</phoneme>'),
            (r'\bKryptojacking\b', r'<phoneme alphabet="ipa" ph="kɾˈyptoː d͡ʒakɪŋ">Kryptojacking</phoneme>'),
            (r'\bMining\b', r'<phoneme alphabet="ipa" ph="mˈa͡ɪnɪŋ">Mining</phoneme>'),
            (r'\bMighty\b', r'<phoneme alphabet="ipa" ph="mˈa͡ɪti">Mighty</phoneme>'),
            (r'\bMalspam\b', r'<phoneme alphabet="ipa" ph="mˈalspam">Malspam</phoneme>'),
            (r'\bSpam\b', r'<phoneme alphabet="ipa" ph="spˈam">Spam</phoneme>'),
            (r'\bSpambot\b', r'<phoneme alphabet="ipa" ph="spˈambɒt">Spambot</phoneme>'),
            (r'\bSpambots\b', r'<phoneme alphabet="ipa" ph="spˈambɒts">Spambots</phoneme>'),
            (r'\bVirtuosin\b', r'<phoneme alphabet="ipa" ph="vˌɪɾtuːoːzˈiːn">Virtuosin</phoneme>'),
            (r'\büblen\b', r'<phoneme alphabet="ipa" ph="ˈyblən">üblen</phoneme>'),
            (r'\bRansomware\b', r'<phoneme alphabet="ipa" ph="ɹˈansəmwˌe͡ə">Ransomware</phoneme>'),
            (r'\Black Friday\b', r'<lang xml:lang="en-US">Black <phoneme alphabet="ipa" ph="ˈfɹaɪˌdeɪ">Friday</phoneme></lang>'),
            (r'\bCyber Monday\b', r'<lang xml:lang="en-US">Cyber Monday</lang>'),
            (r'\bE-Commerce-Websites\b', r'<lang xml:lang="en-US">E-Commerce-Websites</lang>'),
            (r'\bhosten\b', r'<phoneme alphabet="ipa" ph="hˈɔstn">hosten</phoneme>'),
            (r'\bJunk\b', r'<lang xml:lang="en-US"><phoneme alphabet="ipa" ph=" d͡ʒˈʌŋk">Junk</phoneme></lang>'),
            (r'\bBoxing Day\b', r'<lang xml:lang="en-US"><phoneme alphabet="ipa" ph="ˈbɒksɪŋ">Boxing</phoneme> Day</lang>'),
        ]
    },
    "3": {
        "name": "en-au",
        "rules": [
            (r'\bAiTM\b', r'<say-as interpret-as="characters">AiTM</say-as>'),
        ]
    },
    "4": {
        "name": "en-gb",
        "rules": [
            (r'\bAiTM\b', r'<say-as interpret-as="characters">AiTM</say-as>'),
        ]
    },
    "5": {
        "name": "es-es",
        "rules": [
            (r'\bdeep-fake\b', r'<phoneme alphabet="ipa" ph="diːp.feɪk">deep-fake</phoneme>'),
            (r'\bdeep-fakes\b', r'<phoneme alphabet="ipa" ph="diːp.feɪks">deep-fakes</phoneme>'),
            (r'\bMalware\b', r'<phoneme alphabet="ipa" ph="ˈmæl.weɹ">Malware</phoneme>'),
            (r'\bmalvertising\b', r'<phoneme alphabet="ipa" ph="mal.ver.taɪzɪŋ">malvertising</phoneme>'),
            (r'\bSpambots\b', r'<phoneme alphabet="ipa" ph="spˈambots">Spambots</phoneme>'),
            (r'\bstealers\b', r'<phoneme alphabet="ipa" ph="stˈilers">stealers</phoneme>'),
            (r'\bhackean\b', r'<phoneme alphabet="ipa" ph="xa.kˈe.ˌan">hackean</phoneme>'),
            (r'\bhackeado\b', r'<phoneme alphabet="ipa" ph="xakeado">hackeado</phoneme>'),
            (r'\bhackear\b', r'<phoneme alphabet="ipa" ph="xakear">hackear</phoneme>'),
            (r'\bShell\b', r'<phoneme alphabet="ipa" ph="ʒɛl">Shell</phoneme>'),
            (r'\bransomware\b', r'<lang xml:lang="en-US">ransomware</lang>'),
            (r'\bBlack Friday\b', r'<lang xml:lang="en-US">Black Friday</lang>'),
            (r'\bCyber Monday\b', r'<lang xml:lang="en-US">Cyber Monday</lang>'),
            (r'\bPhishing\b', r'<lang xml:lang="en-US">Phishing</lang>'), 
            (r'\barruine\b', r'<phoneme alphabet="ipa" ph="aruˈine">arruíne</phoneme>'),
            (r'\bsmishing\b', r'<lang xml:lang="en-US">smishing</lang>'),
            (r'\bAnyDesk\b', r'<lang xml:lang="en-US">AnyDesk</lang>'),
            (r'\barruíne\b', r'<phoneme alphabet="ipa" ph="aruˈine">arruíne</phoneme>'),
            (r'\bconfiámos\b', r'<phoneme alphabet="ipa" ph="konfjˈamˌos">confiámos</phoneme>'),
        ]
    },
    "6": {
        "name": "es-mx",
        "rules": [
            (r'\bdeepfake\b', r'<phoneme alphabet="ipa" ph="diːp.feɪk">deep-fake</phoneme>'),
            (r'\bdeepfakes\b', r'<phoneme alphabet="ipa" ph="diːp.feɪks">deep-fakes</phoneme>'),
            (r'\bmalvertising\b', r'<phoneme alphabet="ipa" ph="mal.ver.taɪzɪŋ">malvertising</phoneme>'),
            (r'\bSmishing\b', r'<phoneme alphabet="ipa" ph="smɪʎɪŋ">Smishing</phoneme>'),
            (r'\bhackean\b', r'<phoneme alphabet="ipa" ph="xa.kˈe.ˌan">hackean</phoneme>'),
            (r'\bhackeada\b', r'<phoneme alphabet="ipa" ph="xakeada">hackeada</phoneme>'),
            (r'\bhackeado\b', r'<phoneme alphabet="ipa" ph="xakeado">hackeado</phoneme>'),
            (r'\bhackeados\b', r'<phoneme alphabet="ipa" ph="xakeados">hackeados</phoneme>'),
            (r'\bShell\b', r'<phoneme alphabet="ipa" ph="ʒɛl">Shell</phoneme>'),
            (r'\bPhishing\b', r'<lang xml:lang="en-US">Phishing</lang>'), 
            (r'\bFriday\b', r'<phoneme alphabet="ipa" ph="ˈfraiˌdeɪ">Friday</phoneme>'),
            (r'\bMonday\b', r'<phoneme alphabet="ipa" ph="ˈmʌn.deɪ">Monday</phoneme>'),
            (r'\biPhone\b', r'<phoneme alphabet="ipa" ph="ˈaifon">iPhone</phoneme>'),
            (r'\bAnyDesk\b', r'<lang xml:lang="en-US">AnyDesk</lang>'),
            (r'\bCanada Post\b', r'<lang xml:lang="en-US">Canada Post</lang>'),
            (r'\bGmail\b', r'<lang xml:lang="en-US">Gmail</lang>'),
            (r'\bID\b', r'<say-as interpret-as="characters">ID</say-as>'),
            (r'\bTI\b', r'<say-as interpret-as="characters">TI</say-as>'),
        ]
    },
    "7": {
        "name": "fr-ca",
        "rules": [
            (r'\bzombie\b', r'<phoneme alphabet="ipa" ph=" zo.bjə">zombie</phoneme>'),
            (r'\bzombies\b', r'<phoneme alphabet="ipa" ph=" zo.bjə">zombies</phoneme>'),
            (r'\bbot\b', r'<phoneme alphabet="ipa" ph="bɔt">bot</phoneme>'),
            (r'\binfonuagique\b', r'<phoneme alphabet="ipa" ph="ɛ̃fonyaʒik">infonuagique</phoneme>'),
            (r'\bLinkedIn\b', r'<phoneme alphabet="ipa" ph="lɪŋkt.in">LinkedIn</phoneme>'),
            (r'\bmarketing\b', r'<phoneme alphabet="ipa" ph="maʁkɛtɛiɲ">marketing</phoneme>'),
            (r'\bpuppet\b', r'<phoneme alphabet="ipa" ph="pohpɛt">puppet</phoneme>'),
            (r'\bcinq secondes\b', r'<phoneme alphabet="ipa" ph="sɛ̃k søgɔ̃d">cinq secondes</phoneme>'),
            (r'\bsûr\b', r'<phoneme alphabet="ipa" ph="syʁ">sûr</phoneme>'),
            (r'\bregardez y\b', r'<phoneme alphabet="ipa" ph="ɾəgaɾdez‿ i">regardez y</phoneme>'),
            (r'\bWi-Fi\b', r'<phoneme alphabet="ipa" ph="wifi">Wi-Fi</phoneme>'),
            (r'\bicloud\b', r'<phoneme alphabet="ipa" ph="aɪˌklaʊd">icloud</phoneme>'),
        ]
    },
    "8": {
        "name": "fr-fr",
        "rules": [
            (r'\bzombies\b', r'<phoneme alphabet="ipa" ph=" zo.bjə">zombies</phoneme>'),
            (r'\bdeep-fake\b', r'<phoneme alphabet="ipa" ph="diːp.feɪk">deep-fake</phoneme>'),
            (r'\bdeep-fakes\b', r'<phoneme alphabet="ipa" ph="diːp.feɪks">deep-fakes</phoneme>'),
            (r'\bcryptomonnaie\b', r'<phoneme alphabet="ipa" ph="kʁiptɔmɔnɛ">cryptomonnaie</phoneme>'),
            (r'\bregardez y\b', r'<phoneme alphabet="ipa" ph="ɾəgaɾdez‿ i">regardez y</phoneme>'),
        ]
    },
    "9": {
        "name": "it-it",
        "rules": [
            (r'\bleggere\b', r'<phoneme alphabet="ipa" ph="ˈledˈdʒɛre">leggere</phoneme>'),
            (r'\bcomplete\b', r'<phoneme alphabet="ipa" ph="ˈkomˈplɛte">complete</phoneme>'),
            (r'\bfile\b', r'<phoneme alphabet="ipa" ph="fajl">file</phoneme>'),
        ]
    },
    "10": {
        "name": "pl-pl",
        "rules": [
            (r'\bpo to\b', r'<phoneme alphabet="ipa" ph="ˈpɔ.tɔ">po to</phoneme>'),
            (r'\bWord\b', r'<phoneme alphabet="ipa" ph="ˈword">Word</phoneme>'),
            (r'\bSMS-a\b', r'<phoneme alphabet="ipa" ph="ɛsɛˈmɛsa">SMS-a</phoneme>'),
            (r'\bZignorowania\b', r'<phoneme alphabet="ipa" ph="zignorovanja">Zignorowania</phoneme>'),
            (r'\bAiTM\b', r'<phoneme alphabet="ipa" ph="ˈaj.te.em">AiTM</phoneme>'),
            (r'\broutery\b', r'<phoneme alphabet="ipa" ph="ˈru.tery">routery</phoneme>'),
            (r'\bphishingiem\b', r'<phoneme alphabet="ipa" ph="fi.ʃiːn.giem">phishingiem</phoneme>'),
            (r'\be-maili\b', r'<phoneme alphabet="ipa" ph="imejli">e-maili</phoneme>'),
            (r'\be-mailach\b', r'<phoneme alphabet="ipa" ph="imejlach">e-mailach</phoneme>'),
            (r'\bDziękujemy\b', r'<phoneme alphabet="ipa" ph="d͡ʑɛŋkujˈɛmɨ">Dziękujemy</phoneme>'),
            (r'\bcyberzagrożeniami\b', r'<phoneme alphabet="ipa" ph="ˈt͡sɨ.bɛr.za.ɡrɔˈʐɛ.ɲa.mi">cyberzagrożeniami</phoneme>'),
            (r'\bboty\b', r'<phoneme alphabet="ipa" ph="ˈbɔ.tɨ">boty</phoneme>'),
            (r'\be-mailami\b', r'<phoneme alphabet="ipa" ph="iˈmɛj.lami">e-mailami</phoneme>'),
            (r'\bsmartwatche\b', r'<phoneme alphabet="ipa" ph="ˈsmartwɑtʃɛ">smartwatche</phoneme>'),
            (r'\bStealery\b', r'<phoneme alphabet="ipa" ph="ˈsti.lɛ.rɨ">Stealery</phoneme>'),
            (r'\bzidentyfikować\b', r'<phoneme alphabet="ipa" ph="z‿i.dɛn.tɨ.fiˈkɔ.vat͡ɕ">zidentyfikować</phoneme>'),
            (r'\bPodsycanie\b', r'<phoneme alphabet="ipa" ph="pɔd.sɨˈt͡sa.ɲɛ">Podsycanie</phoneme>'),
            (r'\bphishing\b', r'<phoneme alphabet="ipa" ph="ˈfi.ʃiŋɡ">phishing</phoneme>'),
            (r'\bodrzucony\b', r'<phoneme alphabet="ipa" ph="ɔdʐuˈt͡sɔnɨ">odrzucony</phoneme>'),
            (r'\bMMS-y\b', r'<phoneme alphabet="ipa" ph="ɛmɛmˈɛsɨ">MMS-y</phoneme>'),
            (r'\bpodziękowanie\b', r'<phoneme alphabet="ipa" ph="ˌpɔd͡ʑɛ̃ŋkɔˈvaɲɛ">podziękowanie</phoneme>'),
            (r'\bzweryfikować\b', r'<phoneme alphabet="ipa" ph="zvɛrʲiˈfʲikɔvat͡ɕ">zweryfikować</phoneme>'),
        ]
    },
    "11": {
        "name": "pt-br",
        "rules": [
            (r'\bbotnet\b', r'<phoneme alphabet="ipa" ph="bɒt.ˈnɛt">botnet</phoneme>'),
            (r'\bdeepfake\b', r'<phoneme alphabet="ipa" ph="ˈdiːp.feɪk">deepfake</phoneme>'),
            (r'\bcandidate-se\b', r'<phoneme alphabet="ipa" ph="kɐ̃dʒiˈdat͡ʃisi">candidate-se</phoneme>'),
            (r'\bcrypto\b', r'<phoneme alphabet="ipa" ph="ˈkɹɪptʊ">crypto</phoneme>'),
            (r'\bMalware\b', r'<phoneme alphabet="ipa" ph="ˈmæl.weɹ">Malware</phoneme>'),
            (r'\bmalvertising\b', r'<phoneme alphabet="ipa" ph="mælˈvərˌtaɪzɪŋ">malvertising</phoneme>'),
            (r'\bMighty \b', r'<phoneme alphabet="ipa" ph="ˈmaɪti">Mighty </phoneme>'),
            (r'\bmalspam\b', r'<phoneme alphabet="ipa" ph="malspam">malspam</phoneme>'),
            (r'\bpaguem\b', r'<phoneme alphabet="ipa" ph="ˈpaɡej">paguem</phoneme>'),
            (r'\bCFO\b', r'<phoneme alphabet="ipa" ph="ˌsiː.ɛfˈoʊ">CFO</phoneme>'),
            (r'\bSpambot\b', r'<phoneme alphabet="ipa" ph="spˈambɒt">Spambot</phoneme>'),
            (r'\bspear\b', r'<phoneme alphabet="ipa" ph="spɪr">spear</phoneme>'),
            (r'\bStealers\b', r'<phoneme alphabet="ipa" ph="stˈiːlexs">Stealers</phoneme>'),
            (r'\bsozinhos\b', r'<phoneme alphabet="ipa" ph="sozˈiˌɲus">sozinhos</phoneme>'),
            (r'\bcoloca-se\b', r'<phoneme alphabet="ipa" ph="ko.ˈlɔ.ka.si">coloca-se</phoneme>'),
            (r'\babram\b', r'<phoneme alphabet="ipa" ph="ˈabɾɐ̃w">abram</phoneme>'),
            (r'\bPerceba\b', r'<phoneme alphabet="ipa" ph="peɾˈsebɐ">Perceba</phoneme>'),
            (r'\bEste\b', r'<phoneme alphabet="ipa" ph="ˈes.tʃi">Este</phoneme>'),
            (r'\bcartões\b', r'<phoneme alphabet="ipa" ph="kaɾtˌoˈjj̃s">cartões</phoneme>'),
            (r'\bVPNs\b', r'<phoneme alphabet="ipa" ph="vepeˈens">VPNs</phoneme>'),
            (r'\bOracle\b', r'<phoneme alphabet="ipa" ph="ˈɔːrəkəl">Oracle</phoneme>'),
            (r'\bTI\b', r'<say-as interpret-as="characters">TI</say-as>'),
            (r'\be-mail\b', r'<phoneme alphabet="ipa" ph="imˈejl">e-mail</phoneme>'),
        ]
    },
    "12": {
        "name": "pt-pt",
        "rules": [
            (r'\bbotnet\b', r'<phoneme alphabet="ipa" ph="bɒtˈnɛt">botnet</phoneme>'),
            (r'\bDocuSign\b', r'<phoneme alphabet="ipa" ph="dɑkjˈsaɪn">DocuSign</phoneme>'),
            (r'\bguardá-las\b', r'<phoneme alphabet="ipa" ph="guɐɾdaˈlɐʃ">guardá-las</phoneme>'),
            (r'\bredirecionar\b', r'<phoneme alphabet="ipa" ph="ʀədiɾɛsiˈunaɾ">redirecionar</phoneme>'),
            (r'\bcibercriminosos\b', r'<phoneme alphabet="ipa" ph="si.bɨɾ.kɾɨ.mi.ˈno.zuʃ">cibercriminosos</phoneme>'),
            (r'\bspear\b', r'<phoneme alphabet="ipa" ph="spɪə">spear</phoneme>'),
            (r'\binfetado\b', r'<phoneme alphabet="ipa" ph="ĩfɛtˈadu">infetado</phoneme>'),
            (r'\binfetar\b', r'<phoneme alphabet="ipa" ph="ĩfɛtˈar">infetar</phoneme>'),
            (r'\bmultifator\b', r'<phoneme alphabet="ipa" ph="muɫtifatˈor">multifator</phoneme>'),
            (r'\bpush\b', r'<phoneme alphabet="ipa" ph="pʊʃ">push</phoneme>'),
            (r'\bransomware\b', r'<phoneme alphabet="ipa" ph="ˈɾænsəmwɛɹ">ransomware</phoneme>'),
            (r'\bestratagemas\b', r'<phoneme alphabet="ipa" ph="ʃtrɐtɐʒˈemɐʃ">estratagemas</phoneme>'),
            (r'\balojá-las\b', r'<phoneme alphabet="ipa" ph="ɐluʒˈalɐʃ">alojá-las</phoneme>'),
            (r'\binstalá-las\b', r'<phoneme alphabet="ipa" ph="ĩʃtɐlˈalɐʃ">instalá-las</phoneme>'),
            (r'\binfetará\b', r'<phoneme alphabet="ipa" ph="ĩfɘtɐɾˈa">infetará</phoneme>'),
            (r'\bGmail\b', r'<phoneme alphabet="ipa" ph="d͡ʒi.mˈɐjl">Gmail</phoneme>'),
            (r'\bTI\b', r'<say-as interpret-as="characters">TI</say-as>'),
            (r'\brideshare\b', r'<phoneme alphabet="ipa" ph="ɹajdɘʃˈɛɾɘ">rideshare</phoneme>'),
        ]
    },
    "13": {
        "name": "th-th",
        "rules": [
            (r'\bแอปพลิเคชัน\b', r'<phoneme alphabet="ipa" ph="ˌæplɪˈkeɪʃən">แอปพลิเคชัน</phoneme>'),
            (r'\bDocuSign\b', r'<phoneme alphabet="ipa" ph="ˈdɑkiʊsɑin">DocuSign</phoneme>'),
            (r'\bโคร\b', r'<phoneme alphabet="ipa" ph="kʰrōː">โคร</phoneme>'),
            (r'\bมาโคร\b', r'<phoneme alphabet="ipa" ph="maːkʰrō">มาโคร</phoneme>'),
            (r'\bรูปแบบอื่น\b', r'<phoneme alphabet="ipa" ph="rú̋̀p.bàb.eun">รูปแบบอื่น</phoneme>'),
            (r'\bTOAD\b', r'<phoneme alphabet="ipa" ph="toad">TOAD</phoneme>'),
            (r'\bอย่าคลิกลิงก์\b', r'<phoneme alphabet="ipa" ph="yaá̋̀.khliḱ.linḡ">อย่าคลิกลิงก์</phoneme>'),
        ]
    },
    "14": {
        "name": "tr-tr",
        "rules": [
            (r'\bAiTM\b', r'<phoneme alphabet="ipa" ph="a.i.te.me">AiTM</phoneme>'),
            (r'\bASECNA\b', r'<phoneme alphabet="ipa" ph="a‿sekˈ.na">ASECNA</phoneme>'),
            (r'\bbeklenmedik\b', r'<phoneme alphabet="ipa" ph="beklenmeˈdik">beklenmedik</phoneme>'),
            (r'\bbeklenmeyen\b', r'<phoneme alphabet="ipa" ph="beklenmeˈjen">beklenmeyen</phoneme>'),
            (r'\bDeepfake\b', r'<phoneme alphabet="ipa" ph="diip.feejk">Deepfake</phoneme>'),
            (r'\bDocuSign\b', r'<phoneme alphabet="ipa" ph="doˈkjuːsajn">DocuSign</phoneme>'),
            (r'\be-postaya\b', r'<phoneme alphabet="ipa" ph="e.pos.ta.ja">e-postaya</phoneme>'),
            (r'\be-postasını\b', r'<phoneme alphabet="ipa" ph="e.pos.ta.sɯ.nɯ">e-postasını</phoneme>'),
            (r'\be-posta\b', r'<phoneme alphabet="ipa" ph="eːposta">e-posta</phoneme>'),
            (r'\be-postadan\b', r'<phoneme alphabet="ipa" ph="eːpostadan">e-postadan</phoneme>'),
            (r'\bE-postalar\b', r'<phoneme alphabet="ipa" ph="eːpostalar">E-postalar</phoneme>'),
            (r'\be-postalara\b', r'<phoneme alphabet="ipa" ph="eːpostalaɾa">e-postalara</phoneme>'),
            (r'\be-postaları\b', r'<phoneme alphabet="ipa" ph="eːpostalaɾɯ">e-postaları</phoneme>'),
            (r'\be-postaların\b', r'<phoneme alphabet="ipa" ph="eːpostalaɾɯ">e-postaların</phoneme>'),
            (r'\be-postalarının\b', r'<phoneme alphabet="ipa" ph="eːpostalarɯn">e-postalarının</phoneme>'),
            (r'\be-postalarında\b', r'<phoneme alphabet="ipa" ph="eːpostalarɯnda">e-postalarında</phoneme>'),
            (r'\be-postalarını\b', r'<phoneme alphabet="ipa" ph="eːpostalaɾɯnɯ">e-postalarını</phoneme>'),
            (r'\be-postanın\b', r'<phoneme alphabet="ipa" ph="eːpostanɯn">e-postanın</phoneme>'),
            (r'\be-postası\b', r'<phoneme alphabet="ipa" ph="eːpostasɯ">e-postası</phoneme>'),
            (r'\be-postasından\b', r'<phoneme alphabet="ipa" ph="eːpostasɯndan">e-postasından</phoneme>'),
            (r'\beşleşmeyen\b', r'<phoneme alphabet="ipa" ph="eʃleʃmejen">eşleşmeyen</phoneme>'),
            (r'\bhalen\b', r'<phoneme alphabet="ipa" ph="haːlen">halen</phoneme>'),
            (r'\byalnızca\b', r'<phoneme alphabet="ipa" ph="jal.nɯz̥d͡ʒa">yalnızca</phoneme>'),
            (r'\bkısaltmalar\b', r'<phoneme alphabet="ipa" ph="kɯsaltmalaɾ">kısaltmalar</phoneme>'),
            (r'\bolarak\b', r'<phoneme alphabet="ipa" ph="olaɾak">olarak</phoneme>'),
            (r'\bTabi\b', r'<phoneme alphabet="ipa" ph="ta.biː">Tabi</phoneme>'),
            (r'\bçözmelerine\b', r'<phoneme alphabet="ipa" ph="t͡ʃœzmeleɾine">çözmelerine</phoneme>'),
            (r'\be-postalardaki\b', r'<phoneme alphabet="ipa" ph="e.pos.ta.lar.da.kii">e-postalardaki</phoneme>'),
			(r'\be-postalarıyla\b', r'<phoneme alphabet="ipa" ph="e.pos.ta.la.rɯɯj.la">e-postalarıyla</phoneme>'),
			(r'\bPOI\b', r'<phoneme alphabet="ipa" ph="pe.oo.ɯ">POI</phoneme>'),
            (r'\be-postada\b', r'<phoneme alphabet="ipa" ph="e.pos.ta.daː">e-postada</phoneme>'),
            (r'\be-postanıza\b', r'<phoneme alphabet="ipa" ph="e.pos.ta.nɯza">e-postanıza</phoneme>'),
            (r'\be-postadaki\b', r'<phoneme alphabet="ipa" ph="epostadaki">e-postadaki</phoneme>'),
            (r'\be-postalarınız\b', r'<phoneme alphabet="ipa" ph="epostalaɾɯnɯz">e-postalarınız</phoneme>'),
            (r'\be-postasıyla\b', r'<phoneme alphabet="ipa" ph="epostasɯjlaa">e-postasıyla</phoneme>'),
            (r'\byalnızca\b', r'<phoneme alphabet="ipa" ph="jal.nɯz̥d͡ʒa">yalnızca</phoneme>'),
            (r'\be-postalarına\b', r'<phoneme alphabet="ipa" ph="epostalaɾɯna">e-postalarına</phoneme>'),
            (r'\bMMS’yi\b', r'<phoneme alphabet="ipa" ph="meemeeseji">MMS’yi</phoneme>'),
            (r'\bCanada Post’tan\b', r'<phoneme alphabet="ipa" ph="kanaˈda‿postˈtan">Canada Post’tan</phoneme>'),
            (r'\bDHL’den\b', r'<phoneme alphabet="ipa" ph="deːheːleːden">DHL’den</phoneme>'),
            (r'\be-postalarından\b', r'<phoneme alphabet="ipa" ph="epostalarɯndan">e-postalarından</phoneme>'),
            (r'\bFedEx\b', r'<phoneme alphabet="ipa" ph="fˈed‿ˌecs">FedEx</phoneme>'),
            (r'\bİK’den\b', r'<phoneme alphabet="ipa" ph="iːceˈden">İK’den</phoneme>'),
            (r'\bİK’yi\b', r'<phoneme alphabet="ipa" ph="iːceˈji">İK’yi</phoneme>'),
        ]
    },
    "15": {
        "name": "ko-kr",
        "rules": [
            (r'\b슬롯에\b', r'<phoneme alphabet="ipa" ph="sʰɯl‿losʰe">슬롯에</phoneme>'),
            (r'\bAsecna\b', r'<phoneme alphabet="ipa" ph="asekna">Asecna</phoneme>'),
            (r'\bFAA\b', r'<say-as interpret-as="characters">FAA</say-as>'),
        ]
    },
    "16": {
        "name": "sk-sk",
        "rules": [
            (r'\bkyberzločincov\b', r'<phoneme alphabet="ipa" ph="ˈkɪbɛrzlotʃintsɔu">kyberzločincov</phoneme>'),
            (r'\bpostupy\b', r'<phoneme alphabet="ipa" ph="ˈpɔstupi">postupy</phoneme>'),
            (r'\be-mailových\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjloviːx">e-mailových</phoneme>'),
            (r'\be-mailovými\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjloviːmɪ">e-mailovými</phoneme>'),
            (r'\bSMS\b', r'<phoneme alphabet="ipa" ph="ˈesemes">SMS</phoneme>'),
            (r'\bMS Teams\b', r'<phoneme alphabet="ipa" ph="ɛm.ɛs.tiːms">MS Teams</phoneme>'),
            (r'\bphishing\b', r'<phoneme alphabet="ipa" ph="ˈfiʂing">phishing</phoneme>'),
            (r'\bphishingovými\b', r'<phoneme alphabet="ipa" ph="ˈfiʂingɔʋiːmi">phishingovými</phoneme>'),
            (r'\bphishingu\b', r'<phoneme alphabet="ipa" ph="ˈfiʃiŋɡu">phishingu</phoneme>'),
            (r'\be-mailov\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjlɔʋ">e-mailov</phoneme>'),
            (r'\be-mailové\b', r'<phoneme alphabet="ipa" ph="ˈiːmejlɔʋeː">e-mailové</phoneme>'),
            (r'\be-maile\b', r'<phoneme alphabet="ipa" ph="ˈiːmejle">e-maile</phoneme>'),
            (r'\be-maily\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjli">e-maily</phoneme>'),
            (r'\bkyberzločinci\b', r'<phoneme alphabet="ipa" ph="ˈkɪbɛrzlɔtʃɪnt͡si">kyberzločinci</phoneme>'),
            (r'\bcloudové\b', r'<phoneme alphabet="ipa" ph="ˈklau̯dɔʋe">cloudové</phoneme>'),
            (r'\bcloudových\b', r'<phoneme alphabet="ipa" ph="ˈklau̯dɔʋiːx">cloudových</phoneme>'),
            (r'\bmenej\b', r'<phoneme alphabet="ipa" ph="ˈmeɲej">menej</phoneme>'),
            (r'\bprostredníctvom\b', r'<phoneme alphabet="ipa" ph="ˈprɔstrɛdɲiːctʋɔm">prostredníctvom</phoneme>'),
            (r'\bsietnica\b', r'<phoneme alphabet="ipa" ph="ˈsɪetɲitsa">sietnica</phoneme>'),
            (r'\bspoofingu\b', r'<phoneme alphabet="ipa" ph="ˈspuːfingu">spoofingu</phoneme>'),
            (r'\bzariadenia\b', r'<phoneme alphabet="ipa" ph="ˈzarɪɐɟeɲɪɐ">zariadenia</phoneme>'),
            (r'\bID\b', r'<phoneme alphabet="ipa" ph="ˈajdiː">ID</phoneme>'),
            (r'\bPhishingové\b', r'<phoneme alphabet="ipa" ph="ˈfiʃiŋgɔvɛː">Phishingové</phoneme>'),
            (r'\bVictorii\b', r'<phoneme alphabet="ipa" ph="viktˈoːriːˌiː">Victorii</phoneme>'),
            (r'\be-mail\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjl">e-mail</phoneme>'),
            (r'\be-mailmi\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjlmi">e-mailmi</phoneme>'),
            (r'\be-mailoch\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjlɔx">e-mailoch</phoneme>'),
            (r'\be-mailom\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjlɔm">e-mailom</phoneme>'),
            (r'\be-mailová\b', r'<phoneme alphabet="ipa" ph="ˈiːmɛjlɔʋaː">e-mailová</phoneme>'),
            (r'\bmonitorovanie\b', r'<phoneme alphabet="ipa" ph="ˈmɔnitorɔʋaɲɛ">monitorovanie</phoneme>'),
            (r'\bphishingového\b', r'<phoneme alphabet="ipa" ph="ˈfiʃiŋgɔʋɛːɦɔ">phishingového</phoneme>'),
            (r'\bphishingový\b', r'<phoneme alphabet="ipa" ph="ˈfiʃiŋɔʋiː">phishingový</phoneme>'),
            (r'\bphishingových\b', r'<phoneme alphabet="ipa" ph="ˈfiʃiŋɔʋiːx">phishingových</phoneme>'),
            (r'\bphishingovým\b', r'<phoneme alphabet="ipa" ph="ˈfiʃiŋɔʋiːm">phishingovým</phoneme>'),
            (r'\bpoďakovanie\b', r'<phoneme alphabet="ipa" ph="ˈpɔɟakɔʋaɲɛ">poďakovanie</phoneme>'),
        ]
    },
    "17": {
        "name": "sv-se",
        "rules": [
            (r'\boffline\b', r'<phoneme alphabet="ipa" ph="ɑːfˈlaɪn">offline</phoneme>'),
            (r'\bbetrott\b', r'<phoneme alphabet="ipa" ph="bɛˈtrɔt">betrott</phoneme>'),
            (r'\bthe Hall of Hackers\b', r'<phoneme alphabet="ipa" ph="ðə">the</phoneme> <phoneme alphabet="ipa" ph="hɔːl">Hall</phoneme> <phoneme alphabet="ipa" ph="oːf">ofs</phoneme> <phoneme alphabet="ipa" ph="ˈhækərz">Hackers</phoneme>'),
            (r'\bheminternet\b', r'<phoneme alphabet="ipa" ph="hɛmˌɪntɛrnɛt">heminternet</phoneme>'),
            (r'\binvasion\b', r'<phoneme alphabet="ipa" ph="ɪnˈveɪʒən">invasion</phoneme>'),
            (r'\blookalike\b', r'<phoneme alphabet="ipa" ph="lʊkəlaɪk">lookalike</phoneme>'),
            (r'\bmalware\b', r'<phoneme alphabet="ipa" ph="mæl.wer">malware</phoneme>'),
            (r'\brouterns\b', r'<phoneme alphabet="ipa" ph="raʊtɛrnːs">routerns</phoneme>'),
            (r'\bStealers\b', r'<phoneme alphabet="ipa" ph="stiːlərz">Stealers</phoneme>'),
            (r'\bWi-Fi\b', r'<phoneme alphabet="ipa" ph="waɪ.faɪ">Wi-Fi</phoneme>'),
            (r'\be-postalias\b', r'<phoneme alphabet="ipa" ph="ˌɪ.pʊstˈalɪas">e-postalias</phoneme>'),
            (r'\bInvoice\b', r'<phoneme alphabet="ipa" ph="ˈɪnˌvɔɪs">Invoice</phoneme>'),
            (r'\bjulshoppingsäsongen\b', r'<phoneme alphabet="ipa" ph="ˈjʉːlˌʂɔpɪŋˌsɛˌsɔŋɛn ">julshoppingsäsongen</phoneme>'),
        ]
    },
    "18": {
        "name": "da-dk",
        "rules": [
            (r'\bslags\b', r'<phoneme alphabet="ipa" ph="ˈslɑgs">slags</phoneme>'),
            (r'\bmalware\b', r'<phoneme alphabet="ipa" ph="ˈmɑlˌwɛr">malware</phoneme>'),
            (r'\bwi-fi\b', r'<phoneme alphabet="ipa" ph="ˈwɑjˌfɑj">wi-fi</phoneme>'),
            (r'\bAnyDesk\b', r'<phoneme alphabet="ipa" ph="ˈɛnˌi‿dɛsk">AnyDesk</phoneme>'),
            (r'\bE-mailadressen\b', r'<phoneme alphabet="ipa" ph="imeil‿addrˈassn">E-mailadressen</phoneme>'),
            (r'\bVerificér\b', r'<phoneme alphabet="ipa" ph="verifisˈer">Verificér</phoneme>'),
            (r'\bVictoria\b', r'<phoneme alphabet="ipa" ph="vjktˈoɾˌiɑ">Victoria</phoneme>'),
            (r'\bcyberangreb\b', r'<phoneme alphabet="ipa" ph="sɑɪ.ber‿angrˈɛb">cyberangreb</phoneme>'),
            (r'\be-mailadresser\b', r'<phoneme alphabet="ipa" ph="imeil‿addrˈessn">e-mailadresser</phoneme>'),
            (r'\bid\b', r'<say-as interpret-as="characters">id</say-as>'),
            (r'\bpolitikker\b', r'<phoneme alphabet="ipa" ph="politiger">politikker</phoneme>'),
            (r'\bpålideligt\b', r'<phoneme alphabet="ipa" ph="pˌɒ.lidelˈigt">pålideligt</phoneme>'),
        ]
    },
    "19": {
        "name": "ja-jp",
        "rules": [
            (r'\bフィッシング\b', r'<phoneme alphabet="sapi" ph="フィッシング">フィッシング</phoneme>'),
            (r'\b使うよう\b', r'<phoneme alphabet="sapi" ph="ツカウ\'ヨー">使うよう</phoneme>'),
            (r'\b個別連絡\b', r'<phoneme alphabet="sapi" ph="コベツ+レンラク">個別連絡</phoneme>'),
            (r'\b受取ったときに、\b', r'<phoneme alphabet="sapi" ph="ウケトッタトキニ">受取ったときに、</phoneme>'),
            (r'\b確かに\b', r'<phoneme alphabet="sapi" ph="タシカニ">確かに</phoneme>'),
            (r'\b福利厚生\b', r'<phoneme alphabet="sapi" ph="フクリ+コウセイ">福利厚生</phoneme>'),
            (r'\b送信者名\b', r'<phoneme alphabet="sapi" ph="ソウシンシャメイ">送信者名</phoneme>'),
        ]
    },
    "20": {
        "name": "hu-hu",
        "rules": [
            (r'\bAnyDesk\b', r'<phoneme alphabet="ipa" ph="ˈɛni dɛsk">AnyDesk</phoneme>'),
            (r'\bFedEx-et\b', r'<phoneme alphabet="ipa" ph="fɛdɛksɛt">FedEx-et</phoneme>'),
            (r'\badathalász\b', r'<phoneme alphabet="ipa" ph="ɒdɒthɒlaːs">adathalász</phoneme>'),
            (r'\badathalászat\b', r'<phoneme alphabet="ipa" ph="ɒdɒthɒlaːsɒt">adathalászat</phoneme>'),
            (r'\badathalászatot\b', r'<phoneme alphabet="ipa" ph="ɒdɒthɒlaːsɒtot">adathalászatot</phoneme>'),
            (r'\be-mail-cím\b', r'<phoneme alphabet="ipa" ph="iːmeːlt͡siːm">e-mail-cím</phoneme>'),
            (r'\be-mail-címét\b', r'<phoneme alphabet="ipa" ph="iːmeːlt͡siːmeːt">e-mail-címét</phoneme>'),
            (r'\be-mailek\b', r'<phoneme alphabet="ipa" ph="ˈiː.meɪlɛk">e-mailek</phoneme>'),
            (r'\be-mailekben\b', r'<phoneme alphabet="ipa" ph="ˈiː.meɪlɛkbɛn">e-mailekben</phoneme>'),
            (r'\be-maileket\b', r'<phoneme alphabet="ipa" ph="ˈiː.meɪlɛkɛt">e-maileket</phoneme>'),
            (r'\be-mailekről\b', r'<phoneme alphabet="ipa" ph="iːmeːlɛkrøːl">e-mailekről</phoneme>'),
            (r'\be-mailen\b', r'<phoneme alphabet="ipa" ph="ˈiː.meɪlɛn ">e-mailen</phoneme>'),
            (r'\be-maillel\b', r'<phoneme alphabet="ipa" ph="ˈiː.meɪllːɛl">e-maillel</phoneme>'),
            (r'\be-mailre\b', r'<phoneme alphabet="ipa" ph="iːmeːlɾɛ">e-mailre</phoneme>'),
            (r'\be-mailt\b', r'<phoneme alphabet="ipa" ph="ˈiː.meɪlt">e-mailt</phoneme>'),
            (r'\btekintse\b', r'<phoneme alphabet="ipa" ph=" tɛkinʧːɛ">tekintse</phoneme>'),
            (r'\bészre a szokatlan\b', r'<phoneme alphabet="ipa" ph="eːsɾɛ‿ɒ‿sokɒtlɒn">észre a szokatlan</phoneme>'),
        ]
    },
}
