rule_sets = {
    "1": {
        "name": "Spanish",
        "rules": [
          (r'\(?(1)?\)?([-. ]?\d{3}[-. ]\d{3}[-. ]\d{4})', r'<say-as interpret-as="telephone">\1\2</say-as>'),
          (r'\bWaskey\b', r'Wáskey'),
          (r'\bANSI\b', r'Ansi'),
          (r'\bJSEA\b', r'<say-as interpret-as="characters">JSEA</say-as>'),
          (r'\bOsha\b', r'<lang xml:lang="en-US"><phoneme alphabet="ipa" ph="ˈoʃa">Osha</phoneme>'),
          (r'\bPenhall\b', r'<phoneme alphabet="ipa" ph="pˈɛn.hɔl">Penhall</phoneme>'),
          (r'\bProcedure\b', r'<phoneme alphabet="ipa" ph="proˈsidʒur">Procedure</phoneme>'),
          (r'\bcause\b', r'<phoneme alphabet="ipa" ph="ˈkau.se">cause</phoneme>'),
          (r'\bOrion\b', r'<phoneme alphabet="ipa" ph="oˈɾai.on">Orion</phoneme>'),
          (r'\bEngineered\b', r'<phoneme alphabet="ipa" ph="ˌendʒiˈnieɾd">Engineered</phoneme>'),
          (r'\bEscanee\b', r'escané-e'),
          (r'\bFive-S\b', r'Five-eS'),
          (r'Baton', r'Báton'),
          (r'\bAir Liquide\b', r'Air <phoneme alphabet="ipa" ph="likwˈid">Liquide</phoneme>'),
          (r'\bEHS\b', r'<say-as interpret-as="characters">EHS</say-as>'),
          (r'\bEPA\b', r'<say-as interpret-as="characters">EPA</say-as>'),
          (r'\bEPP\b', r'<say-as interpret-as="characters">EPP</say-as>'),
          (r'\bSDS\b', r'<say-as interpret-as="characters">SDS</say-as>'),
          (r'\bexceder\b', r'<phoneme alphabet="ipa" ph="ek.seðˈeɾ">exceder</phoneme>'),
          (r'\binspecciónela\b', r'<phoneme alphabet="ipa" ph="ins.peksjˈo.ne.ˌla">inspecciónela</phoneme>'),
          (r'\brevíselo\b', r'<phoneme alphabet="ipa" ph="revˈiseˌlo">revíselo</phoneme>'),
          (r'\búselas\b', r'<phoneme alphabet="ipa" ph="ˈuselˌas">úselas</phoneme>'),
          (r'\bAlert Enterprise\b', r'<lang xml:lang="en-US">Alert Enterprise</lang>'),
          (r'\bBartow\b', r'<lang xml:lang="en-US">Bartow</lang>'),
          (r'\bJake\b', r'<lang xml:lang="en-US">Jake</lang>'),
          (r'\bMicroEssential\b', r'<lang xml:lang="en-US">MicroEssential</lang>'),
          (r'\bMosaic Fertilizer\b', r'<lang xml:lang="en-US">Mosaic Fertilizer</lang>'),
          (r'\bMosaic Sitehawk\b', r'<lang xml:lang="en-US">Mosaic Sitehawk</lang>'),
          (r'\bMosaic\b(?!\s+(?:Fertilizer|Sitehawk))', r'<lang xml:lang="en-US">Mosaic</lang>'),
          (r'\bNew Wales\b', r'<lang xml:lang="en-US">New Wales</lang>'),
          (r'\bPhosphate Alliance\b', r'<lang xml:lang="en-US">Phosphate Alliance</lang>'),
          (r'\bPlant City\b', r'<lang xml:lang="en-US">Plant City</lang>'),
          (r'\bRiverview\b', r'<lang xml:lang="en-US">Riverview</lang>'),
          (r'\bSouth Pierce\b', r'<lang xml:lang="en-US">South Pierce</lang>'),
          (r'\bTransite\b', r'<lang xml:lang="en-US">Transite</lang>'),
          (r'\bPA\b', r'<say-as interpret-as="characters">PA</say-as>'),
          (r'\bpsi\b', r'<say-as interpret-as="characters">psi</say-as>'),
          (r'\bPine Hall Road, Blues Creek, North Carolina\b', r'<lang xml:lang="en-US">Pine Hall Road, Blues Creek, North Carolina</lang>'),
          (r'\bPine Hall Road\b(?!,\s+Blues Creek,\s+North Carolina)', r'<lang xml:lang="en-US">Pine Hall Road</lang>'),
          (r'\bBlues Creek Steam Station\b', r'<lang xml:lang="en-US">Blues Creek Steam Station</lang>'),
          (r'\bBlues Creek\b(?!\s+(?:Steam Station|(?:,?\s*North Carolina)?))', r'<lang xml:lang="en-US">Blues Creek</lang>'),
          (r'Airport Road', r'<lang xml:lang="en-US">Airport Road</lang>'),
          (r'\bBabcock and Wilcox\b', r'<lang xml:lang="en-US">Babcock and Wilcox</lang>'),
          (r'\bCraig Road\b', r'<lang xml:lang="en-US">Craig Road</lang>'),
          (r'\bDuke Energy\b', r'<lang xml:lang="en-US">Duke Energy</lang>'),
          (r'\bEnergy Way, Hamlet, North Carolina\b', r'<lang xml:lang="en-US">Energy Way, Hamlet, North Carolina</lang>'),
          (r'\bEnterprise Security\b', r'<lang xml:lang="en-US">Enterprise Security</lang>'),
          (r'\bHamlet\b', r'<lang xml:lang="en-US">Hamlet</lang>'),
          (r'\bSherwood H. Smith Jr. Energy Complex\b', r'<lang xml:lang="en-US">Sherwood H. Smith Jr. Energy Complex</lang>'),
          (r'\bDuke Power Plant Steam Road\b', r'<lang xml:lang="en-US">Duke Power Plant Steam Road</lang>'),
          (r'\bSmith Energy Complex\b', r'<lang xml:lang="en-US">Smith Energy Complex</lang>'),
          (r'\bStokes\b', r'<lang xml:lang="en-US">Stokes</lang>'),
          (r'\bWalkertown\b', r'<lang xml:lang="en-US">Walkertown</lang>'),
        ]
    }
}
